version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=cr
      - DB_USERNAME=root
      - DB_PASSWORD=
